all:
  children:
    bootnode:
      hosts:
        vps-01:
          ansible_host: "158.220.127.24"
          region: "EU-Contabo"
    full_node:
      hosts:
        vps-01:
          ansible_host: "158.220.127.24"
          region: "EU-Contabo"
    rpc:
      hosts:
        vps-01:
          ansible_host: "158.220.127.24"
          region: "EU-Contabo"
          rpc_tier: primary
    web:
      hosts:
        vps-01:
          ansible_host: "158.220.127.24"
          region: "EU-Contabo"
    api:
      hosts:
        vps-01:
          ansible_host: "158.220.127.24"
          region: "EU-Contabo"
    faucet:
      hosts:
        vps-01:
          ansible_host: "158.220.127.24"
          region: "EU-Contabo"
    validator:
      hosts:
        vps-02:
          ansible_host: "40.160.87.118"
          region: "US-East"
          validator_address: "0x1a99805b71e0530f774e6b69546cd64e03fc3c33"
        vps-03:
          ansible_host: "217.216.39.77"
          region: "APAC-Singapore"
          validator_address: "0x8a6bff3cedc3d1893740f2453424cd8be2965f1c"
    monitoring:
      hosts:
        vps-03:
          ansible_host: "217.216.39.77"
          region: "APAC-Singapore"
vars:
  # Set true only after DNS, TLS, faucet and all external acceptance checks pass.
  deployment_ready: false
  ansible_user: deployer
  ansible_ssh_private_key_file: ~/.ssh/nakharax-testnet
  container_registry: ghcr.io/axionaxprotocol
  network: public-testnet
