all:
  children:
    bootnode:
      hosts:
        vps-01:
          ansible_host: "158.220.127.24"
          region: "EU-Contabo"
    full_node:
      hosts:
        vps-01:
          ansible_host: "158.220.127.24"
          region: "EU-Contabo"
    rpc:
      hosts:
        vps-01:
          ansible_host: "158.220.127.24"
          region: "EU-Contabo"
          rpc_tier: primary
    web:
      hosts:
        vps-01:
          ansible_host: "158.220.127.24"
          region: "EU-Contabo"
    api:
      hosts:
        vps-01:
          ansible_host: "158.220.127.24"
          region: "EU-Contabo"
    faucet:
      hosts:
        vps-01:
          ansible_host: "158.220.127.24"
          region: "EU-Contabo"
    validator:
      hosts:
        vps-02:
          ansible_host: "40.160.87.118"
          region: "US-East"
          validator_address: "0xca0e4e60f8ce825dbb820c72a7e28e28cdae3326"
        vps-03:
          ansible_host: "217.216.39.77"
          region: "APAC-Singapore"
          validator_address: "0x26e714016c6a91b791bb440ca8db6cd7c4d1e6cb"
    monitoring:
      hosts:
        vps-03:
          ansible_host: "217.216.39.77"
          region: "APAC-Singapore"
vars:
  # Set true only after DNS, TLS, faucet and all external acceptance checks pass.
  deployment_ready: false
  ansible_user: deployer
  ansible_ssh_private_key_file: ~/.ssh/nakharax-testnet
  container_registry: ghcr.io/axionaxprotocol
  network: public-testnet
