#!/usr/bin/env bash
# nakharax-node-bootstrap.sh — build, configure, run, and systemd-install nakharax-node (all roles).
#
# Usage:
#   ./nakharax-node-bootstrap.sh build
#   sudo ./nakharax-node-bootstrap.sh setup --role full --data-dir /var/lib/nakharax-node
#   sudo ./nakharax-node-bootstrap.sh run --data-dir /var/lib/nakharax-node
#   sudo ./nakharax-node-bootstrap.sh install-systemd --data-dir /var/lib/nakharax-node
#   ./nakharax-node-bootstrap.sh doctor --rpc http://127.0.0.1:8545
#
# Environment (optional):
#   NAKHARAX_REPO_ROOT     — repo root if not auto-detected
#   NAKHARAX_BOOTSTRAP_NODES — comma-separated multiaddrs (required for joining public testnet)
#   NAKHARAX_VALIDATOR_ADDRESS — 0x… (required for --role validator)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=node-runtime-common.sh
source "$SCRIPT_DIR/node-runtime-common.sh"

usage() {
  sed -n '1,20p' "$0" | tail -n +2
  cat <<'EOF'

Commands:
  build              — cargo build --release -p node (binary: core/target/release/nakharax-node)
  setup              — create data dir, copy genesis, write node.env + run.sh
  run                — exec nakharax-node using files from --data-dir
  install-systemd    — install and enable nakharax-node.service (uses run.sh in data dir)
  doctor             — curl eth_chainId + eth_blockNumber against --rpc

setup options:
  --role full|rpc|validator|bootnode   (required)
  --data-dir PATH                      (default: /var/lib/nakharax-node as root, else ~/.local/share/nakharax-node)
  --genesis PATH                       (default: core/tools/genesis.json in repo)
  --rpc HOST:PORT                      (default: 0.0.0.0:8545; bootnode default 127.0.0.1:8545)
  --p2p HOST:PORT                      (optional; e.g. 0.0.0.0:30303)
  --bootstrap MULTIADDR               (optional; else set NAKHARAX_BOOTSTRAP_NODES in node.env later)
  --validator-address 0x…            (for validator; or set NAKHARAX_VALIDATOR_ADDRESS)

Examples:
  ./nakharax-node-bootstrap.sh build
  sudo NAKHARAX_BOOTSTRAP_NODES='/ip4/217.216.109.5/tcp/30303/p2p/12D3KooW...' \\
    ./nakharax-node-bootstrap.sh setup --role full --data-dir /var/lib/nakharax-node
  sudo ./nakharax-node-bootstrap.sh run --data-dir /var/lib/nakharax-node
EOF
}

CMD="${1:-}"
shift || true

ROLE=""
DATA_DIR=""
GENESIS_SRC=""
RPC_ADDR=""
P2P_ADDR=""
BOOTSTRAP_ARG=""
VALIDATOR_ADDR=""
RPC_DOCTOR="http://127.0.0.1:8545"

parse_setup_run_flags() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --role) ROLE="$2"; shift 2 ;;
      --data-dir) DATA_DIR="$2"; shift 2 ;;
      --genesis) GENESIS_SRC="$2"; shift 2 ;;
      --rpc) RPC_ADDR="$2"; shift 2 ;;
      --p2p) P2P_ADDR="$2"; shift 2 ;;
      --bootstrap) BOOTSTRAP_ARG="$2"; shift 2 ;;
      --validator-address) VALIDATOR_ADDR="$2"; shift 2 ;;
      --rpc-url) RPC_DOCTOR="$2"; shift 2 ;;
      -h|--help) usage; exit 0 ;;
      *) echo "error: unknown option: $1" >&2; usage; exit 1 ;;
    esac
  done
}

cmd_build() {
  nakharax_resolve_paths
  echo "[build] repo=$NAKHARAX_REPO_ROOT"
  (cd "$NAKHARAX_CORE_DIR" && cargo build --release -p node)
  nakharax_require_binary
  echo "[build] ok: $NAKHARAX_NODE_BIN"
}

default_data_dir() {
  if [[ "$(id -u)" -eq 0 ]]; then
    echo "/var/lib/nakharax-node"
  else
    echo "${HOME}/.local/share/nakharax-node"
  fi
}

cmd_setup() {
  parse_setup_run_flags "$@"
  nakharax_resolve_paths
  nakharax_require_genesis_src

  if [[ -z "$ROLE" ]]; then
    echo "error: setup requires --role full|rpc|validator|bootnode" >&2
    exit 1
  fi
  case "$ROLE" in
    full|rpc|validator|bootnode) ;;
    *) echo "error: invalid --role $ROLE" >&2; exit 1 ;;
  esac

  if [[ -z "${DATA_DIR:-}" ]]; then
    DATA_DIR="$(default_data_dir)"
  fi
  GENESIS_SRC="${GENESIS_SRC:-$NAKHARAX_DEFAULT_GENESIS}"
  if [[ ! -f "$GENESIS_SRC" ]]; then
    echo "error: genesis not found: $GENESIS_SRC" >&2
    exit 1
  fi

  if [[ "$ROLE" == "bootnode" && -z "$RPC_ADDR" ]]; then
    RPC_ADDR="127.0.0.1:8545"
  fi
  RPC_ADDR="${RPC_ADDR:-0.0.0.0:8545}"

  mkdir -p "$DATA_DIR"
  install -m 0644 "$GENESIS_SRC" "$DATA_DIR/genesis.json"

  BOOT="${BOOTSTRAP_ARG:-${NAKHARAX_BOOTSTRAP_NODES:-}}"
  VAL="${VALIDATOR_ADDR:-${NAKHARAX_VALIDATOR_ADDRESS:-}}"

  if [[ "$ROLE" == "validator" && -z "$VAL" ]]; then
    echo "error: validator requires --validator-address or NAKHARAX_VALIDATOR_ADDRESS" >&2
    exit 1
  fi

  cat >"$DATA_DIR/node.env" <<EOF
# Generated by nakharax-node-bootstrap.sh setup — edit NAKHARAX_BOOTSTRAP_NODES before run if empty.
NAKHARAX_ROLE=$ROLE
NAKHARAX_STATE_PATH=$DATA_DIR
NAKHARAX_GENESIS=$DATA_DIR/genesis.json
NAKHARAX_RPC=$RPC_ADDR
NAKHARAX_P2P=${P2P_ADDR:-}
NAKHARAX_BOOTSTRAP_NODES=${BOOT}
NAKHARAX_VALIDATOR_ADDRESS=${VAL}
NAKHARAX_IDENTITY_KEY=$DATA_DIR/identity.key
NAKHARAX_NODE_BIN=$NAKHARAX_NODE_BIN
EOF
  chmod 0600 "$DATA_DIR/node.env" 2>/dev/null || chmod 0644 "$DATA_DIR/node.env"

  if ! nakharax_require_binary 2>/dev/null; then
    echo "warning: binary missing — run: $0 build" >&2
  fi

  # run.sh: load node.env then exec binary (systemd-friendly ExecStart)
  cat >"$DATA_DIR/run.sh" <<'EOS'
#!/usr/bin/env bash
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
set -a
# shellcheck disable=SC1090
source "$HERE/node.env"
set +a
if [[ -z "${NAKHARAX_BOOTSTRAP_NODES:-}" ]]; then
  echo "warning: NAKHARAX_BOOTSTRAP_NODES is empty — public testnet peers may not connect" >&2
fi
export NAKHARAX_BOOTSTRAP_NODES
ARGS=(
  --role "$NAKHARAX_ROLE"
  --chain "$NAKHARAX_GENESIS"
  --rpc "$NAKHARAX_RPC"
  --state-path "$NAKHARAX_STATE_PATH"
  --identity-key "$NAKHARAX_IDENTITY_KEY"
)
if [[ -n "${NAKHARAX_P2P:-}" ]]; then
  ARGS+=(--p2p "$NAKHARAX_P2P")
fi
if [[ -n "${NAKHARAX_VALIDATOR_ADDRESS:-}" ]]; then
  ARGS+=(--validator-address "$NAKHARAX_VALIDATOR_ADDRESS")
fi
exec "$NAKHARAX_NODE_BIN" "${ARGS[@]}"
EOS

  chmod 0755 "$DATA_DIR/run.sh"

  echo "[setup] data-dir=$DATA_DIR"
  echo "[setup] role=$ROLE genesis=$DATA_DIR/genesis.json rpc=$RPC_ADDR"
  if [[ -z "$BOOT" ]]; then
    echo "[setup] Edit $DATA_DIR/node.env and set NAKHARAX_BOOTSTRAP_NODES= (comma-separated multiaddrs)"
  fi
  echo "[setup] Run: sudo $0 run --data-dir $DATA_DIR"
  echo "        or: sudo $0 install-systemd --data-dir $DATA_DIR"
}

cmd_run() {
  DATA_DIR=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --data-dir) DATA_DIR="$2"; shift 2 ;;
      -h|--help) usage; exit 0 ;;
      *) echo "error: unknown option: $1" >&2; exit 1 ;;
    esac
  done
  if [[ -z "${DATA_DIR:-}" ]]; then
    DATA_DIR="$(default_data_dir)"
  fi
  if [[ ! -x "$DATA_DIR/run.sh" ]]; then
    echo "error: $DATA_DIR/run.sh not found — run setup first" >&2
    exit 1
  fi
  exec "$DATA_DIR/run.sh"
}

cmd_install_systemd() {
  DATA_DIR=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --data-dir) DATA_DIR="$2"; shift 2 ;;
      -h|--help) usage; exit 0 ;;
      *) echo "error: unknown option: $1" >&2; exit 1 ;;
    esac
  done
  if [[ -z "${DATA_DIR:-}" ]]; then
    DATA_DIR="$(default_data_dir)"
  fi
  if [[ ! -x "$DATA_DIR/run.sh" ]]; then
    echo "error: $DATA_DIR/run.sh not found — run setup first" >&2
    exit 1
  fi
  if [[ "$(id -u)" -ne 0 ]]; then
    echo "error: install-systemd must run as root" >&2
    exit 1
  fi
  local unit="/etc/systemd/system/nakharax-node.service"
  cat >"$unit" <<EOF
[Unit]
Description=Nakharax nakharax-node ($DATA_DIR)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$DATA_DIR
ExecStart=$DATA_DIR/run.sh
Restart=always
RestartSec=10
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable nakharax-node.service
  echo "[install-systemd] wrote $unit"
  echo "[install-systemd] systemctl start nakharax-node"
}

cmd_doctor() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --rpc|--rpc-url) RPC_DOCTOR="$2"; shift 2 ;;
      -h|--help) usage; exit 0 ;;
      *) RPC_DOCTOR="$1"; shift ;;
    esac
  done
  echo "[doctor] RPC=$RPC_DOCTOR"
  curl -sf -X POST -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' "$RPC_DOCTOR" | head -c 200 || {
    echo "error: chainId request failed" >&2
    exit 1
  }
  echo ""
  curl -sf -X POST -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' "$RPC_DOCTOR" | head -c 200 || {
    echo "error: blockNumber request failed" >&2
    exit 1
  }
  echo ""
  echo "[doctor] ok"
}

case "$CMD" in
  build) cmd_build "$@" ;;
  setup) cmd_setup "$@" ;;
  run) cmd_run "$@" ;;
  install-systemd) cmd_install_systemd "$@" ;;
  doctor) cmd_doctor "$@" ;;
  ""|-h|--help) usage ;;
  *) echo "error: unknown command: $CMD" >&2; usage; exit 1 ;;
esac
